#!/usr/bin/python3

def raise_exception_msg(message=""):
    raise TypeError("Ce nom n'existe pas")
